SELECT 'TWC' AS BILLER, CREATE_DTE_OOR AS CREATE_DTE, ORD_STAT_OOR AS ORD_STAT, CONCAT ('#', ORDER_NO_OOR) AS ORDER_NO, 
CONCAT ('#', FROM_SUB_ACCT_NO_CAT) AS FROM_SUB_ACCT_NO,
CONCAT ('#', TO_SUB_ACCT_NO_CAT) AS TO_SUB_ACCT_NO,
CASE WHEN CUSTOM_FIELD05_OOR='G' THEN 'GATEWAY' 
     WHEN CUSTOM_FIELD05_OOR=' ' THEN 'BILLER' 
     WHEN CUSTOM_FIELD05_OOR='A' THEN 'STVA' ELSE CUSTOM_FIELD05_OOR END AS SOURCE,
     CREATE_OP_ID_OOR,
     MGMTAREANAME,
     ENTITYACCOUNT,
     FIRSTNAME,
     LASTNAME
FROM OPS$TWC.CAT_CUST_ACCT_TRANSFER

LEFT JOIN 
(SELECT SYS_OOR, PRIN_OOR, AGNT_OOR, CREATE_DTE_OOR, CUSTOM_FIELD05_OOR, CUST_ACCT_NO_OOR, HSE_KEY_OOR, ORDER_NO_OOR, 
CREATE_OP_ID_OOR, ORD_STAT_OOR
FROM 
(
SELECT SYS_OOR, PRIN_OOR, AGNT_OOR, CREATE_DTE_OOR, CUSTOM_FIELD05_OOR, CUST_ACCT_NO_OOR, HSE_KEY_OOR, ORDER_NO_OOR, 
CREATE_OP_ID_OOR, ORD_STAT_OOR
FROM OPS$TWC.OOR_ORDER_OPEN 

)
ON CREATE_TRANS_DTE_CAT= CREATE_DTE_OOR
AND FROM_SYS_CAT = SYS_OOR
AND FROM_PRIN_CAT = PRIN_OOR
AND FROM_AGNT_CAT = AGNT_OOR
AND FROM_CUST_ACCT_NO_CAT = CUST_ACCT_NO_OOR
AND FROM_HSE_KEY_CAT = HSE_KEY_OOR

JOIN UXID ON CSGOPID = CREATE_OP_ID_OOR

;